namespace CookingEnums
{
    public enum CookingState
    {
        Idle,
        Cooking,
        Done,
        Interrupted
    }

    public enum IngredientState
    {
        Raw,
        Prepared
    }

    public enum CookingType
    {
        None,
        Boil,
        Fry,
        Bak,
        Chopp,
        Grate,
        Pour
    }
    public enum RawIngredients
    {
        CottageCheese,
        Milk,
        Eggs,
        Buttter,
        SourCream,
        Flour,
        BakingPowder,
        Rice,
        Sugar,
        Salt,
        Pepper,
        PowderedSugar,
        VanillaExtract,
        BayLeaf,
        Vinegar,
        Cherries,
        Jam,
        Onion,
        Carrots,
        Garlic,
        Mushrooms,
        Cabbage,
        Potato,
        Tomato,
        Zucchini,
        Spinach,
        ShiitakeMushrooms,
        BeanSprouts,
        Beef,
        Bacon,
        RedWine,
        BeefBroth,
        TomatoPaste,
        Oil,
        GochujiangSauce,
        SoySauce,
        Beetroot
    }

    public enum PreparedIngredients
    {
        Boiled_Potato,
        Fried_Potato,
        Baked_Potato,
        Chopped_Potato,
        Grated_Potato,
        Boiled_Carrot,
        Fried_Carrot,
        Baked_Carrot,
        Chopped_Carrot,
        Grated_Carrot,
        Boiled_Onion,
        Fried_Onion,
        Baked_Onion,
        Chopped_Onion,
        Grated_Onion,
        Boiled_Meat,
        Fried_Meat,
        Baked_Meat,
        Chopped_Meat,
        Grated_Meat,
        Boiled_Fish,
        Fried_Fish,
        Baked_Fish,
        Chopped_Fish,
        Grated_Fish,
        Boiled_Egg,
        Fried_Egg,
        Baked_Egg,
        Chopped_Egg,
        Grated_Egg
    }
    public enum FinalDishes
    {
        Syrnyky,
        Varenyky,
        Papanasi,
        BeefBourguignon,
        Borscht,
        Bibimbap
    }
}
